### ISSUE TITLE
(feature-request): Make PacketsReceiptNotificationsValue configurable

### ISSUE THREAD

**Issue by alfabetagama** [EinfachHans/cordova-plugin-dfu-update#5]
PacketsReceiptNotificationsValue is currently hardcoded at 10 in:

https://github.com/EinfachHans/cordova-plugin-dfu-update/blob/931d2976b4b0678785b4ec2f66fb82e3b39da8dd/src/android/DfuUpdate.java#L111

and 

https://github.com/EinfachHans/cordova-plugin-dfu-update/blob/931d2976b4b0678785b4ec2f66fb82e3b39da8dd/src/ios/DfuUpdate.swift#L101

We have some devices that need this set to 1, so we propose that  PacketsReceiptNotificationsValue is set via:
https://github.com/EinfachHans/cordova-plugin-dfu-update/blob/931d2976b4b0678785b4ec2f66fb82e3b39da8dd/src/ionic/index.js#L8 

as additional parameter:

`DfuUpdate.updateFirmware = function (resultCallback, errorCallback, fileURL, deviceIdentifier, packetReceiptNotificationsValue)`

**Comment by EinfachHans** [comment]
Can you explain me more about what this Parameter means? I developed/forked this Plugin to work with our current environment and want to understand this change

**Comment by alfabetagama** [comment]
Thanks for quick response. Here is link to documantation:

https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v11.0.0%2Fbledfu_transport_bleservice.html

And description:

Number of PacketsInformation: Parameter value for the Packet Receipt Notification Request Op Code | C1 | uint16 | Number of packets of firmware data to be received by the DFU target before sending a new Packet Receipt Notification (control point notification with Op Code = 7). If this value is 0, the packet receipt notification will be disabled by the DFU target.
-- | -- | -- | --

**Comment by EinfachHans** [comment]
Ok thank you. I will look into this and release a update the next days!

**Comment by alfabetagama** [comment]
@EinfachHans thanks, looking forward to it.

**Comment by EinfachHans** [comment]
Just released Version **1.3.0**, which includes the availability to set an extra Option: packetReceiptNotificationsValue
Please notice that this is a Breaking Change as the Options are now all included into a JSON (See [Usage](https://github.com/EinfachHans/cordova-plugin-dfu-update#updatefirmware))

Thanks for using 😊 If you have time would be great if you can like my PR to Include a Ionic Wrapper for this Plugin [here](https://github.com/ionic-team/ionic-native/pull/3514)

**Comment by alfabetagama** [comment]
Thanks. Great work! I will try to test it on android today.
