### ISSUE TITLE
Use plugin with ionic 3

### ISSUE THREAD

**Issue by sunnymtl** [EinfachHans/cordova-plugin-dfu-update#6]
We are trying to use this plugin in an ionic 3 project. Now we can successfully do DFU through nFR connect mobile, the DFU target should work well. 

When we call updateFirmware(), it return both "success" and "error", and the DFU is not performed. Does this command do the same thing like what the nFR connect perform DFU, or do we need to do something extra?

Does this plugin work with [randdusing/cordova-plugin-bluetoothle](https://github.com/randdusing/cordova-plugin-bluetoothle)? this is the plugin we are currently using for BLE.

Thanks a lot for the help!

**Comment by EinfachHans** [comment]
I did use this Plugin in combination with the ble plugin without problems. I'm on the latest Ionic Version but this should not cause any issues.

**Comment by apkanwar** [comment]
I am getting a similar error with this plugin. It returns a success and failure callback after running updateFirmware().

After using the Ionic file chooser and Ionic File Path libraries to get the correct file path on my android device, I run the updateFirmware(). 

For nRF Connect, the DFU update accepts .bin files. Does this plugin for ionic accept .bin files or just .zip files.

In any case the error I get is: 
- Error: 4097
- ErrorType: 0
- Message: DFU FILE NOT FOUND

Thanks.

**Comment by EinfachHans** [comment]
@apkanwar pls share some code. This Plugin is just a wrapper of the native libraries so please read their documentation about format & error codes.

I'm using a .zip File

**Comment by apkanwar** [comment]
![image](https://user-images.githubusercontent.com/15526213/131908627-40051a95-6038-4c04-93c8-909946556e7a.png)

Is this the correct format for how to use the function in angular?

Thanks.

**Comment by EinfachHans** [comment]
how does `resolvedPath` looks like?

**Comment by apkanwar** [comment]
![image](https://user-images.githubusercontent.com/15526213/131909389-1b8b9f40-d41e-47e5-979c-5f06bfc99d04.png)

Line 1 is the uri
Line 2 is the resolved path
Line 3 is the Success callback
Link 4 is the Error Callback

**Comment by EinfachHans** [comment]
Did you try a .zip File?

Also please post the output of the first success object.

Also please do **never** (not here or anywhere else) post code in an image. Please post Code and Console Output via the Markdown Code Formation

**Comment by apkanwar** [comment]
Unfortunately, I do not have a zip file for my current project. 

I will send what the success object after modifying the code.

Noted: will do code in Markdown for the future.

**Comment by EinfachHans** [comment]
I think a zip is expected if i remember correctly

**Comment by Saadzbilal** [comment]
@apkanwar Are you able to resolve this path issue? or are you using .bin file or .zip? can you help regarding file path in android

**Comment by Saadzbilal** [comment]
> I think a zip is expected if i remember correctly

@EinfachHans Same error for .zip file in android
error: 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/104424953/172559187-6f38a0a6-0914-4a2e-8c2e-f729e695cc24.png">
 filePath in android: fileUrl: 'file:///storage/emulated/0/Download/firmware2.zip',
 can you help what is the problem here?

**Comment by mmccorkle-accesso** [comment]
Any updates on this? I have the same problem using your File nativeURL to retrieve the file on Android. 

```
Reconnected from DFU update. Updating firmware now. file:///data/user/0/com.myapp/files/RVI002BP2.zip
nordic.service.ts:345 Checking if file exists: file:///data/user/0/com.myapp/files/RVI002BP2.zip
nordic.service.ts:350 Sending update with file at native path: file:///data/user/0/com.myapp/files/RVI002BP2.zip
nordic.service.ts:348 Local file system URL: {"isFile":true,"isDirectory":false,"name":"RVI002BP2.zip","fullPath":"/RVI002BP2.zip","filesystem":"<FileSystem: files>","nativeURL":"file:///data/user/0/com.myapp/files/RVI002BP2.zip"}
nordic.service.ts:358 updateFirmware res: {"id":"F2:76:BB:74:58:93","status":"deviceDisconnected"}
nordic.service.ts:365 updateFirmware error: {"id":"F2:76:BB:74:58:93","error":4097,"errorType":0,"message":"DFU FILE NOT FOUND"}
```

**Comment by markamccorkle** [comment]
Any updates on this? I have the same problem using your File nativeURL to retrieve the file on Android. 

```
Reconnected from DFU update. Updating firmware now. file:///data/user/0/com.myapp/files/RVI002BP2.zip
nordic.service.ts:345 Checking if file exists: file:///data/user/0/com.myapp/files/RVI002BP2.zip
nordic.service.ts:350 Sending update with file at native path: file:///data/user/0/com.myapp/files/RVI002BP2.zip
nordic.service.ts:348 Local file system URL: {"isFile":true,"isDirectory":false,"name":"RVI002BP2.zip","fullPath":"/RVI002BP2.zip","filesystem":"<FileSystem: files>","nativeURL":"file:///data/user/0/com.myapp/files/RVI002BP2.zip"}
nordic.service.ts:358 updateFirmware res: {"id":"F2:76:BB:74:58:93","status":"deviceDisconnected"}
nordic.service.ts:365 updateFirmware error: {"id":"F2:76:BB:74:58:93","error":4097,"errorType":0,"message":"DFU FILE NOT FOUND"}
```
